version: '3.7'
services:
  mysql:
    container_name: node-docker-3
    image: node-docker-2
    build:
      context: .
      dockerfile: ./dockerfile.mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - 3300:3300
  m1:
    depends_on:
      - mysql
    container_name: node-docker-3
    image: node-docker-2
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
