version: '3.7'

services:
  react:
    depends_on:
        - app
    container_name: plataforma-jogos-react
    image: plataforma-jogos
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3006:3006
    networks:
      - plataforma-jogos

networks:
  plataforma-jogos: